# Basic Site Settings
locale                   : "en-US"
site_theme               : "air"
title                    : "Mohammad Malekpouri | AI & Genetics Researcher"
title_separator          : "-"
name                     : &name "Mohammad Malekpouri"
description              : &description "AI & Genetics Researcher | Full Stack Developer"
url                      : "https://malekpouri.github.io"
baseurl                  : "" 
repository               : "malekpouri/malekpouri.github.io"

# Site Author - Sidebar Info
author:
  avatar           : "profile1.jpg"
  name             : "Mohammad Malekpouri"
  pronouns         :  
  bio              : "A dedicated software engineer and researcher passionate about applying AI and machine learning to the fascinating world of genetics and computational biology."
  location         : "Iran, Bnd"
  employer         : ""
  uri              : 
  email            : "malekpoor@aut.ac.ir" 

  # Academic websites
  googlescholar    : "" # اگر لینک داری می‌تونم اضافه کنم
  orcid            : "https://orcid.org/0009-0001-6278-6163"
  researchgate     : ""
  scopus           : ""

  # Repositories and software development
  github           : "malekpouri"

  # Social media
  linkedin         : "malekpouri"
  bluesky          : "malekpouri.bsky.social"
  twitter          : ""  
  telegram         : ""  

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :  
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

atom_feed:
  hide                   : false     

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : 
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  
og_description           :  
social:
  type                   : Person
  name                   : "Mohammad Malekpouri"
  links: 
    - "https://github.com/malekpouri"
    - "https://www.linkedin.com/in/malekpouri"
    - "https://orcid.org/0009-0001-6278-6163"
    - "https://bsky.app//malekpouri.bsky.social"

# Analytics
analytics:
  provider               : false 

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_: true
      share: true
      comments: false
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_: true
      share: true
      comments: false
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_: true
      share: true
      comment: false
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Asia/Tehran

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
